[project]
name = "yeti-iga"
version = "0.0.1"
authors = [
    { name="Arnaud Duval", email="arnaud.duval@cnrs.fr" },
]
description = "Yeti is an IGA code"
requires-python = ">=3.10"
license = { file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Fortran",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: POSIX :: Linux",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
dependencies = ["numpy<=1.26.4", "scipy>=1.13"]

[project.urls]
Homepage = "https://lamcosplm.insa-lyon.fr/projects/yeti"
Issues = "https://lamcosplm.insa-lyon.fr/plugins/tracker/?tracker=626"

[build-system]
requires = ["scikit-build-core", "numpy"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.version = ">=3.17.2"
cmake.verbose = true
logging.level =  "INFO"

[tool.ruff]
src = ["src"]
