name: Build & Deploy Docs

on:
  workflow_run:
    workflows: ["Publish to PyPI"]
    types: [completed]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        startsWith(github.event.workflow_run.head_branch, 'v')
      }}
    steps:
      - name: Trigger Read the Docs
        run: |
            curl -X POST \
                 -d "token=${{ secrets.RTD_TOKEN }}" \
                 https://app.readthedocs.org/api/v2/webhook/yeti-iga-documentation/310200/

