name: Publish to PyPI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]        # A tag startingwith v (e.g. v0.1.2) will trigger the publication
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build all wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (for cibuildwheel tool)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install buils deps
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels (all target Pythons)
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "cp38-* *musllinux*"
        run: |
          echo "CIBW-BUILD=$CIBW_BUILD"
          cibuildwheel --platform linux --output-dir wheelhouse
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*.whl
        
  test:
    name: Test wheel on multiple Pythons
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist
      
      - name: Set up Python for test
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install wheel and run tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          # Get ABI CPxx of current Python version (ex : cp312)
          PYTAG=$(python -c "import sys; print(f'cp{sys.version_info[0]}{sys.version_info[1]}')")
          echo "Installing wheel for $PYTAG"
          # Install wheel with this tag
          pip install dist/*${PYTAG}*.whl
          pytest benchs
    

  publish:
    name: Publish to PyPI
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')   # seulement pour un tag
    steps:
      - uses: actions/checkout@v4
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
