name: Build, test & publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]        # A tag startingwith v (e.g. v0.1.2) will trigger the publication
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build all wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (for cibuildwheel tool)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install buils deps
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels (all target Pythons)
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "cp36-* cp37-* cp38-* *musllinux*"
        run: |
          echo "CIBW-BUILD=$CIBW_BUILD"
          cibuildwhell --platform linux --output-dir wheelhouse
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*.whl
        


  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')   # seulement pour un tag
    steps:
      - uses: actions/checkout@v4
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
